### PR TITLE
SIP-11: Action Primitive

### PR DESCRIPTION
**Pull request by cubicgames-dev**

### CODE REVIEW

**Comment by damirka** [comment]
@cubicgames-dev

Thank you for your engaging proposal; it's both intriguing and well-detailed! However, I do have a few areas where I'd love to gain a deeper understanding:

- In the context of on-chain actions like creating pools, adding liquidity, or setting up accounts, I'm curious about the specific use cases where introducing extra objects with the Action Primitive would prove particularly beneficial. My Account or an LP token or a "Bullshark" serve as a proof of action already, is there a need to introduce something new?

- To provide more context and enhance our discussions, it would be great if you could share 1-2 real-world scenarios that showcase the practical applications of this feature.

- While the RewardsPool is mentioned as part of the specification, I'm interested in whether reward distribution is the primary use case for the Action Primitive, or if there are scenarios where it can be applied independently of rewards.

- If not for rewards, what are the use cases where one would want to store the proof of activity on chain?  

Your insights would be greatly appreciated as we delve deeper into your proposal. Please feel free to share your thoughts, and let's continue this productive conversation!

**Comment by cubicgames-dev** [comment]
@damirka 

Thank you for the feedback! We'd love to share our thoughts on the questions you posted.

**Q1**: In the context of on-chain actions like creating pools, adding liquidity, or setting up accounts, I'm curious about the specific use cases where introducing extra objects with the Action Primitive would prove particularly beneficial. My Account or an LP token or a "Bullshark" serve as a proof of action already, is there a need to introduce something new?

It's worth mentioning that not every on-chain activity comes with a certifying object, such as trading, voting and so on. The introduction of action objects could be seen as an abstract layer that is universally interoperable.

---

**Q2**: To provide more context and enhance our discussions, it would be great if you could share 1-2 real-world scenarios that showcase the practical applications of this feature.

Take our platform Cubic as an example. As one of our offerings, we host irregular voting campaign with selected partner protocols to increase their exposure. Incentives play an essential part in our case to encourage participation, with reward distribution taking the form of fixed prize pool or lottery.

To implement such incentive scheme without invading business logics, we typically need to index emitted events off chain and enact distribution rules in a centralized server, which is far from ideal in terms of transparency and trustless-ness. With `Action` and `Action Attestation` in the SIP in place, we would easily migrate distribution fully on-chain, in which users are guaranteed for fair distribution of rewards as long as their actions are deemed valid by respective `Attester` modules. 

Two different `Attester` modules will be set up in our case:
- campaign attester: Cubic as a platform, setups a global reward pool to encourage participation for a campaign
- candidate attester: candidates can setup reward pools to bribe votes for themselves

Once users receive `Attestation` from `Attester` modules, they can enroll reward distribution in reward pools that accept these `Attestation`. The specific distribution mechanism could be fixed prize pool, lottery-based whatsoever.

---

**Q3**: While the `RewardPool` is mentioned as part of the specification, I'm interested in whether reward distribution is the primary use case for the Action Primitive, or if there are scenarios where it can be applied independently of rewards.

To clarify, the way we construct Action Primitive is with `Action` objects at the core and various extensions built around it. One of such extension we proposed in the SIP is `Action Attestation`. And `RewardPool` is one of the components in this extension. We agree it may be too specific and it could make more sense to extract it out from the specification.

At this stage, reward distribution appears the most practical use case for Action Primitive to drive adoption, thus we design `Action Attestation` extension targeted at that specific use case.

---

**Q4**: If not for rewards, what are the use cases where one would want to store the proof of activity on chain?

Although we consider the use case of reward distribution as an adoption driver for Action Primitive, the design space is not limited to this.

In essence, `Action` objects can be beneficial to any protocol that requires knowledge of a user's on-chain activities in an interoperable manner without depending on off-chain event indexing services. Any layers built upon Action Primitive are trust-minimized by nature since `Actions` are data assets owned by users and accessible to any party they authorize.

Let's dabble on some of these potential scenarios.

**Scenario 1**
Eligible Sui stakers can claim membership to some exclusive community on the condition that:
	1. Time weighted staking balance > A
	2. Staked to more than B different validators

An `Attester` module can be implemented to validate all these rules via metadata associated with Staking `Actions`. An eligible user could simply pass along all related `Actions` he owns for eligibility checking without trusting results given by some centralized service.

**Scenario 2**
On the other spectrum, `Actions` can also be used as building blocks for future Decentralized Identity protocols, which may involve use cases like on-chain reputation system, under-collateralized loans, action explorer, etc.

**Comment by damirka** [comment]
Hey @cubicgames-dev, thank you for such an elaborate response! What do you see as the outcome of this proposal? Do you see it becoming a module in the Sui Framework or an agreement on practices?

**Comment by SA124** [comment]
Hello @cubicgames-dev  

Thanks for your SIP proposal. In order to process the SIP, the SIP Editor requires write access to the forked repository in order to change the status and add additional information.

Could you please grant write access on the forked repository to the following GitHub accounts?

- SA124
- wriches

Once this has been completed, we can move the proposal forward.

Best regards, 
Shereen

**Comment by SA124** [comment]
Hello @cubicgames-dev

Thanks for your SIP proposal. In order to process the SIP, the SIP Editor requires write access to the forked repository in order to change the status and add additional information.

Could you please grant write access on the forked repository to the following GitHub accounts?

SA124
wriches
Once this has been completed, we can move the proposal forward.

Best regards,
Shereen

**Comment by wriches** [comment]
SIP withdrawn due to inactivity

**Review by wriches — APPROVED** [review]

**Pull request merged**
