### PR TITLE
Create SIP - Structured Derivative Standard: A Novel Financial Instru…

### PR DESCRIPTION
**Pull request by highsea-protocol**
Create SIP - Structured Derivative Standard: A Novel Financial Instru…

### CODE REVIEW

**Comment by sblackshear** [comment]
Thanks for submitting this!

One thing I did not understand from the proposal is where this requires code changes in the Sui core code, RPCs, or SDK's. Would you mind elaborating on that point?

**Comment by highsea-protocol** [comment]
> Thanks for submitting this!
> 
> One thing I did not understand from the proposal is where this requires code changes in the Sui core code, RPCs, or SDK's. Would you mind elaborating on that point?

Thank you for your review and your question!

The Structured Derivative Standard proposal is primarily focused on the application layer. It introduces new types of smart contracts and asset interactions without necessitating changes to the Sui core code, RPCs, or SDKs.

However, to enable end-users to fully engage with these new structured derivatives and financial instruments, some updates may be required for the Sui Wallet and other wallets that support Sui. These updates will mainly involve recognizing and accurately displaying the newly introduced structured derivative assets.

These wallet updates are similar to the ones implemented when ERC-721 (NFTs) or ERC-1155 were introduced on Ethereum. They require wallets to accommodate a new asset type. Apart from these wallet updates, we anticipate that the core Sui protocol and associated tooling will not need to be modified to support this new standard.

I hope this clarifies your concerns. We are thrilled about the potential of the Structured Derivative Standard and eagerly look forward to collaborating with the Sui community to make it a reality.

**Comment by hyd628** [comment]
@highsea-protocol Since this does not require any changes in the core Sui code base, I would recommend this to be closed, and you can open a PR in the Sui Wallet repo.

**Comment by SA124** [comment]
Closing this proposal due to lack of activity.

**Pull request closed without merging**
