### PR TITLE
SIP to add store ability to Pool struct.

### PR DESCRIPTION
**Pull request by Rajwanshi1**

### CODE REVIEW

**Comment by sblackshear** [comment]
I don't see any immediate problems with this from the DeepBook side.

The main thing questions I would ask would be:
1. whether coupling tightly to the implementation quirks of DeepBook `Pool`'s is a good idea for third-party protocols
2. whether this coupling will lead to pressure to make changes that make sense for the third-party protocols, but not for DeepBook in the future (leading to frustration on one or both sides).

On (1), the things I wonder about are the burned pool creation fee of 100 SUI (third-party protocols might not want it, or might want a different fee) and the "burn trading fees rather than collecting them" scheme, which seem someone DeepBook-idiosyncratic. I would expect that some third-party protocols would want a different fee, to collect the fee rather than burn it, etc.

On (2), this is of course a hypothetical concern, but is motivated by the desire to allow other `Pool` implementations to evolve in the way that makes sense. One concrete scenario to think through:
- In the future, say a third-party protocol X wants to add a function that allows the funds in `quote_asset_trading_fees` to fund grants for building on X (very reasonable)
- DeepBook does not want this function to exist, because its fees are burned (also reasonable)
- There's no way to distinguish DeepBook pools from third-party pools at the code level, so someone would be left upset

**Comment by sblackshear** [comment]
Two questions to think about given the above:
A. What are the pros/cons of creating a separate copy of the `Pool` code for third-party protocols to customize/publush as they see fit, rather than reusing the DeepBook code?
B. If reusing DeepBook `Pool`s does make sense, should we add a `PoolOwnerCap` that can be used for extracting fees in third-party protocols + make the API for creating a shared DeepBook pool immediately burn this cap?

**Comment by healthydeve** [comment]
> Two questions to think about given the above: A. What are the pros/cons of creating a separate copy of the `Pool` code for third-party protocols to customize/publish as they see fit, rather than reusing the DeepBook code? B. If reusing DeepBook `Pool`s does make sense, should we add a `PoolOwnerCap` that can be used for extracting fees in third-party protocols + make the API for creating a shared DeepBook pool immediately burn this cap?

A. Pros: 
Having the changes contained in deepbook core will allow the entire community + us at mysten to review the changes to the deepbook code. We can guarantee that the changes are audited + well tested. This prevents community members from nefariously forking the code and claiming "This is a deepbook fork" while bumping up fees in some capacity or something of the sort. 

I think deepbook should still charge 100 SUI pool creation fees for the following reaons:
 - discourage the usage of pools indiscriminately (i.e. spamming the network with pool objects, especially since right now we cannot delete a shared object)
 -  We are charging for the infrastructure of building deepbook + maintaining deepbook. 
 
 However, by giving future fees generated by deepbook to the protocol building on top, these protocols will eventually earn the 100 sui fee back.

Cons: 
- We need to create future proof pool work where changes are generic enough to support multiple protocols. 
- The emitting of events is still a problem since wrapping Pool in a different smart contract will cause events to be emitted under a separate package (but maybe this could be a feature not a bug to distinguish protocols)

B. I do think we should add this feature to encourage usage of deepbook as a primitive.

**Comment by sblackshear** [comment]
> I do think we should add this feature to encourage usage of deepbook as a primitive.

This seems like the most important argument--I did not previously realize that the absence of `store` basically makes nontrival integration of third-party protocols with DeepBook impossible. Strongly supportive of this SIP now!

**Comment by healthydeve** [comment]
https://github.com/MystenLabs/sui/pull/14398

Closing this SIP

**Pull request closed without merging**
