### PR TITLE
SIP-33: Allow inactive StakedSui objects to be redeemed immediately

### PR DESCRIPTION
**Pull request by 0xripleys**

### CODE REVIEW

**Comment by sblackshear** [comment]
This looks simple/reasonable enough to me, but I cannot remember the context for why we have the `stake_activation_epoch(&staked_sui) <= ctx.epoch().

@emmazzz, was it to make the amount of new stake that will become active in the next epoch for a given validator more predictable (i.e., because you could do a big `request_add_stake` early in the epoch and then pull it at the last second without this assertion)? This doesn't seem like a significant protection (particularly because you can already churn stake by withdrawing existing stake at the last second), but I might be forgetting the reasoning or missing something.

**Comment by emmazzz** [comment]
> This looks simple/reasonable enough to me, but I cannot remember the context for why we have the `stake_activation_epoch(&staked_sui) <= ctx.epoch().
> @emmazzz, was it to make the amount of new stake that will become active in the next epoch for a given validator more predictable (i.e., because you could do a big request_add_stake early in the epoch and then pull it at the last second without this assertion)? This doesn't seem like a significant protection (particularly because you can already churn stake by withdrawing existing stake at the last second), but I might be forgetting the reasoning or missing something.

I also don't remember the exact context. I think it might be related to potentially adding unbonding period, but bonding period can certainly still be implemented without this assertion too. So I'm cool with this change too.

**Comment by hyd628** [comment]
This has been implemented and merged in https://github.com/MystenLabs/sui/pull/18265

Closing as accepted and merged.

**Comment by emmazzz** [comment]
I thought final SIPs were supposed to be merged in, instead of closed? @hyd628

**Review by wriches — APPROVED** [review]

**Pull request merged**
