### PR TITLE
Add SIP for Dependency Update Check API

### PR DESCRIPTION
**Pull request by kairoski03**
Hello,
This SIP suggests APIs for dependency update check.
Thank you.

### CODE REVIEW

**Comment by kairoski03** [comment]
@wriches Hello, I changed copyright to use CCO 1.0.
Thanks.

**Comment by kairoski03** [comment]
@AndrewGalak6578 Hello, maybe API providers who implement the API spec will appear and they will maintain and update
following up the changes.

**Comment by hyd628** [comment]
Similar to [my notes](https://github.com/sui-foundation/sips/pull/3#issuecomment-1654637102) for SIP-3, while this feature would be very useful to have, it shouldn't be an SIP, as it doesn't involve any changes to core Sui Move codebase or otherwise an ecosystem level change.

This can also just be a PR to the Sui explorer or as a standalone service that can be integrated into wallets and explorers. 

Due to the above reasons, I would recommend not moving this proposal to the next stage.

If you have any questions about this, please reach out to me on TG.

**Comment by hyd628** [comment]
Inactive and feature already implemented.

**Pull request merged**
