### PR TITLE
New struct MatchedOrderMetadata in DeepBook

### PR DESCRIPTION
**Pull request by Rajwanshi1**
SIP to propose MatchedOrderMetadata to be returned from deepbook place order functions.

### CODE REVIEW

**Comment by SA124** [comment]
Hello @Rajwanshi 

Thanks for your SIP proposal. In order to process the SIP, the SIP Editor requires write access to the forked repository in order to change the status and add additional information.

Could you please grant write access on the forked repository to the following GitHub accounts?

SA124
shayansanjideh

Once this has been completed, we can move the proposal forward.

Best regards,
Shereen

**Comment by sblackshear** [comment]
Thanks @Rajwanshi1, the motivation is well explained and the proposal for addressing this makes sense to me!

Could you add an example for what a client calling one of the `_metadata` functions that return `MatchedOrderMetadata`'s might look like? I think it would be very useful for folks to see how this is intended to be used, and >1 example might make sense if there are multiple usage (e.g., if the usage for spot vs leverage looks different).

My only main questions are about implementation details in https://github.com/MystenLabs/sui/pull/15119 
- Do callers need all of the fields in `MatchedOrderMetadata` for the proposed use-case(es)? In particular, do they need `taker_commission` and `maker_rebates`?
- I'm concerned about the amount of code duplication in functions like `place_limit_order_with_metadata` w.r.t `place_limit_order`. I think it would be ideal if these functions called the same internal helper, and the only difference is that one drops the `MatchedOrderMetadata` while the other forwards it to the caller
- I'm concerned about the behavior changes w.r.t gas on the old functions like `place_limit_order`. Clients of this code that are close to limits might end up bumping into a higher bucket or running out of gas. Have you measured the difference in gas usage, and if it's significant, should we consider only computing the metadata on control-flow paths that need it (and, e.g., returning an empty vector otherwise)?

**Comment by Rajwanshi1** [comment]
> * case

1. ```taker_commission``` and ```maker_rebates``` are required to calculate exact amounts of quantities credited/deducted from maker & takers account caps along with base qty filled and price. So exposing these values could be helpful for deterministic calcs. 
2. [https://github.com/MystenLabs/sui/pull/15273]
3. [https://github.com/MystenLabs/sui/pull/15275]

**Comment by Rajwanshi1** [comment]
> Hello @Rajwanshi
> 
> Thanks for your SIP proposal. In order to process the SIP, the SIP Editor requires write access to the forked repository in order to change the status and add additional information.
> 
> Could you please grant write access on the forked repository to the following GitHub accounts?
> 
> SA124 shayansanjideh
> 
> Once this has been completed, we can move the proposal forward.
> 
> Best regards, Shereen

Hi @SA124 , I've provided access to our fork.

**Comment by amogh-sui** [comment]
Hey @Rajwanshi1 

Thanks for the SIP. I am the editor for the SIP and need to update its status based on the subsequent discussions. Could you please give me write access to the forked repo?

Thanks

**Comment by amogh-sui** [comment]
The status of SIP-14 has been updated and the SIP is now officially under review.

**Comment by dariorussi** [comment]
I believe this is merged in and has been approved and it's currently live.
@Rajwanshi1 can you confirm?

**Comment by dariorussi** [comment]
.... and as a consequence I think this can be closed...

**Review by wriches — APPROVED** [review]

**Pull request merged**
